import { useEffect, useMemo, useState } from 'react'
import type { Session, User } from '@supabase/supabase-js'
import { ChefHat, Dices, House, ListChecks, LogOut, ShoppingCart, UserRound, UtensilsCrossed, CalendarDays, Heart, Plus, Share2, Trash2, Pencil, RotateCcw, UsersRound, KeyRound, X, Check, ArrowRight, LoaderCircle } from 'lucide-react'
import { api } from './lib/api'
import { cleanRecipeText, mergeIngredientNames } from './lib/ingredients'
import { pickRandomDish } from './lib/random'
import { shareShoppingList } from './lib/share'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import type { Dish, Household, MealPlanItem, ShoppingList } from './types'

type View = 'home' | 'today' | 'dishes' | 'plan' | 'shopping' | 'household' | 'profile'
const arabicError = (message: unknown) => message instanceof Error && message.message.includes('Invalid login') ? 'البريد الإلكتروني أو كلمة المرور غير صحيحة.' : message instanceof Error ? message.message : 'حدث خطأ غير متوقع.'
const days = ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد']
const isoDate = (offset: number) => { const now = new Date(); const monday = new Date(now); monday.setDate(now.getDate() - ((now.getDay() + 6) % 7) + offset); return monday.toISOString().slice(0, 10) }

function Button({ children, onClick, kind = 'primary', type = 'button', disabled = false }: { children: React.ReactNode; onClick?: () => void; kind?: 'primary'|'soft'|'danger'|'icon'; type?: 'button'|'submit'; disabled?: boolean }) { return <button type={type} className={`button ${kind}`} onClick={onClick} disabled={disabled}>{children}</button> }
function Empty({ icon = '🍲', children }: { icon?: string; children: React.ReactNode }) { return <div className="empty"><span>{icon}</span><p>{children}</p></div> }

function Auth({ onSession }: { onSession: (session: Session) => void }) {
  const [mode, setMode] = useState<'login'|'signup'|'reset'>('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!supabase) return; setBusy(true); setNotice(''); try { if (mode === 'reset') { await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/` }); setNotice('أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.'); } else if (mode === 'signup') { const { data, error } = await supabase.auth.signUp({ email, password, options: { data: { display_name: name }, emailRedirectTo: `${window.location.origin}/` } }); if (error) throw error; if (data.session) onSession(data.session); else setNotice('تحقق من بريدك الإلكتروني لتأكيد الحساب، ثم سجّل الدخول.'); } else { const { data, error } = await supabase.auth.signInWithPassword({ email, password }); if (error) throw error; onSession(data.session); } } catch (error) { setNotice(arabicError(error)) } finally { setBusy(false) } }
  return <main className="auth-page"><div className="brand"><ChefHat size={52}/><h1>مطبخنا</h1><p>طبخٌ أسهل، وبيتٌ أكثر ترتيباً.</p></div><form className="card auth-card" onSubmit={submit}><h2>{mode === 'login' ? 'تسجيل الدخول' : mode === 'signup' ? 'إنشاء حساب' : 'استعادة كلمة المرور'}</h2>{mode === 'signup' && <label>الاسم الظاهر<input required maxLength={80} value={name} onChange={(e) => setName(e.target.value)} placeholder="مثال: أمينة" /></label>}<label>البريد الإلكتروني<input required type="email" dir="ltr" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="بريدك الإلكتروني" /></label>{mode !== 'reset' && <label>كلمة المرور<input required minLength={8} type="password" dir="ltr" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="ثمانية أحرف على الأقل" /></label>}{notice && <p className="notice">{notice}</p>}<Button type="submit" disabled={busy}>{busy ? <LoaderCircle className="spin"/> : mode === 'login' ? 'دخول' : mode === 'signup' ? 'إنشاء الحساب' : 'إرسال الرابط'}</Button><div className="auth-links">{mode === 'login' ? <><button type="button" onClick={() => setMode('signup')}>حساب جديد</button><button type="button" onClick={() => setMode('reset')}>نسيت كلمة المرور؟</button></> : <button type="button" onClick={() => setMode('login')}>العودة لتسجيل الدخول</button>}</div></form></main>
}

export default function App() {
  const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { if (!supabase) { setLoading(false); return } ; supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe() }, [])
  if (loading) return <div className="center-loading"><LoaderCircle className="spin"/> جارٍ التحميل…</div>
  if (!isSupabaseConfigured) return <main className="auth-page"><div className="brand"><ChefHat size={52}/><h1>مطبخنا</h1><p>التطبيق جاهز، وتحتاج هذه النسخة إلى إعداد الاتصال الآمن بالخدمة.</p></div><div className="card"><h2>إعداد مطلوب</h2><p className="muted">أضف متغيرَي البيئة الآمنين للخدمة ثم أعد تشغيل التطبيق.</p></div></main>
  return session ? <Shell user={session.user} deletionConfirmed={new URLSearchParams(window.location.search).get('account_deletion') === 'confirm'} onLogout={async () => { await supabase?.auth.signOut() }} /> : <Auth onSession={setSession}/>
}

function Shell({ user, onLogout, deletionConfirmed }: { user: User; onLogout: () => Promise<void> | void; deletionConfirmed: boolean }) {
  const [households, setHouseholds] = useState<Household[]>([]); const [household, setHousehold] = useState<Household | null>(null); const [view, setView] = useState<View>('home'); const [busy, setBusy] = useState(true); const [error, setError] = useState('')
  const refreshHouseholds = async () => { try { setBusy(true); const rows = await api.households(); setHouseholds(rows); setHousehold((current) => rows.find((row) => row.id === current?.id) ?? rows[0] ?? null) } catch (e) { setError(arabicError(e)) } finally { setBusy(false) } }
  useEffect(() => { refreshHouseholds() }, [])
  if (busy) return <div className="center-loading"><LoaderCircle className="spin"/> جارٍ تجهيز مطبخك…</div>
  if (!household) return <Onboard user={user} onDone={refreshHouseholds} error={error}/>
  const common = { household, user, onError: setError }
  const content = view === 'home' ? <Home {...common} go={setView}/> : view === 'today' ? <Today {...common}/> : view === 'dishes' ? <Dishes {...common}/> : view === 'plan' ? <Plan {...common}/> : view === 'shopping' ? <Shopping {...common}/> : view === 'household' ? <HouseholdView {...common} households={households} changeHousehold={setHousehold} onRefresh={refreshHouseholds}/> : <Profile user={user} onLogout={onLogout} go={setView} onError={setError} deletionConfirmed={deletionConfirmed}/>
  return <div className="app-shell">{error && <div className="error-banner" role="alert">{error}<button onClick={() => setError('')} aria-label="إغلاق"><X size={18}/></button></div>}<header><div><span className="eyebrow">{household.name}</span><h1>مطبخنا <span>🍲</span></h1></div><button className="avatar" onClick={() => setView('profile')} aria-label="الملف الشخصي"><UserRound size={20}/></button></header><main className="content">{content}</main><nav className="bottom-nav" aria-label="التنقل الرئيسي"><Nav icon={<House/>} label="الرئيسية" active={view === 'home'} onClick={() => setView('home')}/><Nav icon={<Dices/>} label="اليوم" active={view === 'today'} onClick={() => setView('today')}/><Nav icon={<UtensilsCrossed/>} label="الأكلات" active={view === 'dishes'} onClick={() => setView('dishes')}/><Nav icon={<CalendarDays/>} label="الأسبوع" active={view === 'plan'} onClick={() => setView('plan')}/><Nav icon={<ShoppingCart/>} label="التسوّق" active={view === 'shopping'} onClick={() => setView('shopping')}/><Nav icon={<UsersRound/>} label="العائلة" active={view === 'household'} onClick={() => setView('household')}/></nav></div>
}
function Nav({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active: boolean; onClick: () => void }) { return <button className={active ? 'active' : ''} onClick={onClick}>{icon}<span>{label}</span></button> }
function Onboard({ user, onDone, error }: { user: User; onDone: () => Promise<void>; error: string }) { const [name, setName] = useState(''); const [code, setCode] = useState(''); const [busy, setBusy] = useState(false); const [localError, setLocalError] = useState(''); const perform = async (task: () => Promise<unknown>) => { setBusy(true); setLocalError(''); try { await task(); await onDone() } catch (e) { setLocalError(arabicError(e)) } finally { setBusy(false) } }; return <main className="auth-page"><div className="brand"><House size={48}/><h1>أهلاً بك</h1><p>أنشئ بيتك أو انضم إلى بيت عائلتك.</p></div>{(error || localError) && <p className="notice">{localError || error}</p>}<section className="card"><h2>أنشئ منزلاً</h2><label>اسم المنزل<input maxLength={80} value={name} onChange={(e) => setName(e.target.value)} placeholder="مثال: بيت العائلة"/></label><Button disabled={busy || !name.trim()} onClick={() => perform(() => api.createHousehold(name))}><Plus/>إنشاء المنزل</Button></section><section className="card"><h2>انضم برمز الدعوة</h2><label>رمز الدعوة<input dir="ltr" maxLength={16} value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="ABCDEF1234567890"/></label><Button kind="soft" disabled={busy || code.length < 16} onClick={() => perform(() => api.joinHousehold(code))}><KeyRound/>انضمام</Button></section><p className="muted">مسجّل باسم {user.email}</p></main> }

type Context = { household: Household; user: User; onError: (error: string) => void }
function Home({ household, go }: Context & { go: (view: View) => void }) { return <><section className="hero"><span>🍛</span><p>أهلاً بكم في {household.name}</p><h2>ماذا نطبخ اليوم؟</h2></section><div className="action-grid"><button onClick={() => go('today')}><Dices/><strong>اختيار اليوم</strong><small>دعوا الحظ يختار</small></button><button onClick={() => go('dishes')}><UtensilsCrossed/><strong>الأكلات</strong><small>أضيفوا وصفاتكم</small></button><button onClick={() => go('plan')}><CalendarDays/><strong>خطة الأسبوع</strong><small>رتّبوا الأيام</small></button><button onClick={() => go('shopping')}><ShoppingCart/><strong>قائمة التسوّق</strong><small>تُزامن مع العائلة</small></button><button onClick={() => go('household')}><UsersRound/><strong>العائلة</strong><small>رمز الدعوة والأعضاء</small></button></div><section className="card tip"><Heart size={19}/><p>يمكن لكل أفراد المنزل إضافة الأكلات وتحديث قائمة التسوّق فوراً.</p></section></> }
function useDishes(householdId: string, onError: (message: string) => void) { const [dishes, setDishes] = useState<Dish[]>([]); const [loading, setLoading] = useState(true); const refresh = async () => { try { setLoading(true); setDishes(await api.dishes(householdId)) } catch (e) { onError(arabicError(e)) } finally { setLoading(false) } }; useEffect(() => { refresh() }, [householdId]); return { dishes, loading, refresh } }

function Today({ household, onError }: Context) { const { dishes, loading } = useDishes(household.id, onError); const [favoriteOnly, setFavoriteOnly] = useState(false); const [category, setCategory] = useState(''); const [excluded, setExcluded] = useState<string[]>([]); const [choice, setChoice] = useState<Dish | undefined>(); const candidates = useMemo(() => dishes.filter((dish) => (!favoriteOnly || dish.is_favorite) && (!category || dish.category === category)), [dishes, favoriteOnly, category]); const categories = [...new Set(dishes.map((dish) => dish.category).filter(Boolean))]; const roll = () => setChoice(pickRandomDish(candidates, excluded));
  if (loading) return <Loading/>; return <><section className="page-title"><Dices/><div><h2>ماذا نطبخ اليوم؟</h2><p>اختيار سريع يناسب جميع أفراد البيت.</p></div></section><section className="card filters"><label className="switch"><input type="checkbox" checked={favoriteOnly} onChange={(e) => setFavoriteOnly(e.target.checked)}/><span/>المفضّلة فقط</label><label>الفئة<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">كل الفئات</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></label></section>{!dishes.length ? <Empty>أضيفوا أكلة أولاً، ثم دعوا الحظ يساعدكم.</Empty> : <><Button onClick={roll}><Dices/>اختيار عشوائي</Button>{choice && <section className="choice card"><span>✨ اقتراح اليوم</span><h2>{choice.name}</h2>{choice.description && <p>{choice.description}</p>}<div className="choice-actions"><Button kind="soft" onClick={roll}><RotateCcw/>اختيار آخر</Button><Button kind="icon" onClick={() => { setExcluded((items) => [...items, choice.id]); roll() }}><X/>استبعاد</Button></div></section>}<p className="muted">{candidates.length - excluded.filter((id) => candidates.some((dish) => dish.id === id)).length} أكلات متاحة للاختيار.</p></>}</> }

function Dishes({ household, user, onError }: Context) { const { dishes, loading, refresh } = useDishes(household.id, onError); const [editing, setEditing] = useState<Dish | null | undefined>(undefined); const [query, setQuery] = useState(''); const remove = async (dish: Dish) => { if (!window.confirm(`هل تريد حذف «${dish.name}»؟`)) return; try { await api.deleteDish(dish.id); await refresh() } catch (e) { onError(arabicError(e)) } }; if (editing !== undefined) return <DishForm household={household} user={user} dish={editing} onCancel={() => setEditing(undefined)} onSaved={async () => { await refresh(); setEditing(undefined) }} onError={onError}/>; if (loading) return <Loading/>; const filtered = dishes.filter((dish) => dish.name.includes(query) || dish.category.includes(query)); return <><section className="page-title"><UtensilsCrossed/><div><h2>الأكلات</h2><p>{dishes.length} أكلة في هذا المنزل</p></div><Button kind="icon" onClick={() => setEditing(null)}><Plus/></Button></section><input className="search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="ابحث عن أكلة…"/>{!filtered.length ? <Empty>{query ? 'لا توجد نتائج مطابقة.' : 'لم تضيفوا أكلات بعد.'}</Empty> : <div className="dish-list">{filtered.map((dish) => <article className="dish-row" key={dish.id}><button className="dish-main" onClick={() => setEditing(dish)}><div><h3>{dish.name} {dish.is_favorite && <Heart className="favorite" size={16}/>}</h3><p>{dish.category || 'بدون فئة'} · {dish.ingredients.length} مكوّنات</p></div><ArrowRight/></button><div className="row-actions"><button aria-label="تعديل" onClick={() => setEditing(dish)}><Pencil size={17}/></button><button aria-label="حذف" className="delete" onClick={() => remove(dish)}><Trash2 size={17}/></button></div></article>)}</div>}</> }

function DishForm({ household, user, dish, onCancel, onSaved, onError }: Context & { dish: Dish | null; onCancel: () => void; onSaved: () => Promise<void> }) { const [name, setName] = useState(dish?.name ?? ''); const [description, setDescription] = useState(dish?.description ?? ''); const [category, setCategory] = useState(dish?.category ?? ''); const [favorite, setFavorite] = useState(dish?.is_favorite ?? false); const [rawIngredients, setRawIngredients] = useState(dish?.ingredients.map((item) => `${item.quantity_text} ${item.name}`.trim()).join('\n') ?? ''); const [busy, setBusy] = useState(false); const save = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return onError('اكتب اسم الأكلة أولاً.'); const cleaned = cleanRecipeText(rawIngredients); setBusy(true); try { await api.saveDish(household.id, user.id, { id: dish?.id, name, description, category, is_favorite: favorite }, cleaned.map((item, position) => ({ name: item, quantity_text: '', position }))); await onSaved() } catch (e) { onError(arabicError(e)) } finally { setBusy(false) } }; return <form onSubmit={save}><section className="page-title"><button type="button" className="back" onClick={onCancel}><ArrowRight/></button><div><h2>{dish ? 'تعديل أكلة' : 'أكلة جديدة'}</h2><p>أضيفوا كل مكوّن في سطر.</p></div></section><section className="card form"><label>اسم الأكلة<input autoFocus required maxLength={120} value={name} onChange={(e) => setName(e.target.value)} placeholder="مثال: مقلوبة"/></label><label>الوصف<textarea maxLength={2000} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="وصف قصير اختياري"/></label><label>الفئة<input maxLength={60} value={category} onChange={(e) => setCategory(e.target.value)} placeholder="مثال: غداء"/></label><label className="switch"><input type="checkbox" checked={favorite} onChange={(e) => setFavorite(e.target.checked)}/><span/>أضف إلى المفضّلة</label><label>المكوّنات<textarea rows={9} value={rawIngredients} onChange={(e) => setRawIngredients(e.target.value)} placeholder={'٢ كوب أرز\nنصف كيلو باذنجان\nملعقة كبيرة بهارات'}/></label><p className="muted">تُنظّف المقادير تلقائياً لتسهيل دمج العناصر في قائمة التسوّق.</p></section><Button type="submit" disabled={busy}><Check/>حفظ الأكلة</Button></form> }

function Plan({ household, user, onError }: Context) { const { dishes } = useDishes(household.id, onError); const [plans, setPlans] = useState<MealPlanItem[]>([]); const [loading, setLoading] = useState(true); const refresh = async () => { try { setLoading(true); setPlans(await api.mealPlan(household.id, isoDate(0), isoDate(6))) } catch (e) { onError(arabicError(e)) } finally { setLoading(false) } }; useEffect(() => { refresh() }, [household.id]); const byDate = new Map(plans.map((item) => [item.plan_date, item])); const set = async (date: string, dishId: string) => { try { await api.setPlan(household.id, user.id, date, dishId); await refresh() } catch (e) { onError(arabicError(e)) } }; const makeList = async () => { const names = mergeIngredientNames(plans.flatMap((item) => item.dishes?.ingredients.map((ingredient) => ingredient.name) ?? [])); if (!names.length) return onError('أضيفوا أكلات إلى الخطة أولاً.'); try { await api.createShoppingList(household.id, user.id, names); window.location.hash = 'shopping'; alert('تم إنشاء قائمة التسوّق المشتركة.'); } catch (e) { onError(arabicError(e)) } }; if (loading) return <Loading/>; return <><section className="page-title"><CalendarDays/><div><h2>خطة الأسبوع</h2><p>من الاثنين إلى الأحد</p></div></section><div className="plan-list">{days.map((day, index) => { const date = isoDate(index); const item = byDate.get(date); return <article className="plan-day" key={date}><div><strong>{day}</strong><small>{new Intl.DateTimeFormat('ar', { day: 'numeric', month: 'short' }).format(new Date(`${date}T12:00:00`))}</small></div>{item ? <div className="planned"><span>{item.dishes?.name}</span><button aria-label="حذف من الخطة" onClick={async () => { try { await api.deletePlan(item.id); await refresh() } catch (e) { onError(arabicError(e)) } }}><X size={17}/></button></div> : <select aria-label={`اختر أكلة ليوم ${day}`} value="" onChange={(e) => e.target.value && set(date, e.target.value)}><option value="">اختر أكلة</option>{dishes.map((dish) => <option key={dish.id} value={dish.id}>{dish.name}</option>)}</select>} {!item && dishes.length > 0 && <button className="random-mini" aria-label="اقتراح عشوائي" onClick={() => { const dish = pickRandomDish(dishes); if (dish) set(date, dish.id) }}><Dices size={17}/></button>}</article>})}</div><Button kind="soft" onClick={makeList}><ListChecks/>إنشاء قائمة تسوّق للأسبوع</Button></> }

function Shopping({ household, user, onError }: Context) { const [list, setList] = useState<ShoppingList | null>(null); const [loading, setLoading] = useState(true); const [newItem, setNewItem] = useState(''); const refresh = async () => { try { setLoading(true); setList(await api.shoppingList(household.id)) } catch (e) { onError(arabicError(e)) } finally { setLoading(false) } }; useEffect(() => { refresh() }, [household.id]); const create = async () => { try { await api.createShoppingList(household.id, user.id, []); await refresh() } catch (e) { onError(arabicError(e)) } }; if (loading) return <Loading/>; if (!list) return <><section className="page-title"><ShoppingCart/><div><h2>قائمة التسوّق</h2><p>مشتركة مع أفراد المنزل</p></div></section><Empty icon="🛒">أنشئوا قائمة جديدة أو أنشئوها من أكلة أو خطة الأسبوع.</Empty><Button onClick={create}><Plus/>إنشاء قائمة جديدة</Button></>; const add = async (event: React.FormEvent) => { event.preventDefault(); if (!newItem.trim()) return; try { await api.addShoppingItem(list.id, newItem); setNewItem(''); await refresh() } catch (e) { onError(arabicError(e)) } }; const items = list.shopping_items ?? []; return <><section className="page-title"><ShoppingCart/><div><h2>قائمة التسوّق</h2><p>{items.filter((item) => !item.checked).length} عناصر متبقية</p></div><Button kind="icon" onClick={() => shareShoppingList('مطبخنا', items.filter((item) => !item.checked).map((item) => item.name)).catch((e) => onError(arabicError(e)))}><Share2/></Button></section><form className="add-item" onSubmit={add}><input value={newItem} onChange={(e) => setNewItem(e.target.value)} maxLength={160} placeholder="أضف عنصراً إلى القائمة…"/><button aria-label="إضافة"><Plus/></button></form>{!items.length ? <Empty icon="✅">القائمة فارغة الآن.</Empty> : <div className="shopping-items">{items.map((item) => <div className={item.checked ? 'checked' : ''} key={item.id}><button className="check-item" aria-label={item.checked ? 'إلغاء التأشير' : 'تأشير العنصر'} onClick={async () => { try { await api.updateShoppingItem(item.id, { checked: !item.checked }); await refresh() } catch (e) { onError(arabicError(e)) } }}>{item.checked && <Check size={16}/>}</button><span>{item.name}</span><button aria-label="حذف العنصر" onClick={async () => { try { await api.deleteShoppingItem(item.id); await refresh() } catch (e) { onError(arabicError(e)) } }}><Trash2 size={16}/></button></div>)}</div>}<Button kind="soft" onClick={async () => { try { await api.resetShoppingList(list.id); await refresh() } catch (e) { onError(arabicError(e)) } }}><RotateCcw/>إعادة ضبط علامات القائمة</Button></> }

function HouseholdView({ household, households, changeHousehold, onRefresh, onError }: Context & { households: Household[]; changeHousehold: (household: Household) => void; onRefresh: () => Promise<void> }) { const [members, setMembers] = useState<{ user_id: string; role: string; profiles?: { display_name: string } | null }[]>([]); useEffect(() => { api.members(household.id).then(setMembers).catch((e) => onError(arabicError(e))) }, [household.id]); const copy = async () => { try { await navigator.clipboard.writeText(household.invite_code); alert('تم نسخ رمز الدعوة.') } catch { onError('تعذر نسخ الرمز. انسخه يدوياً.') } }; return <><section className="page-title"><UsersRound/><div><h2>المنزل</h2><p>إدارة أفراد المنزل والدعوات</p></div></section><section className="card invite"><p>رمز الدعوة</p><strong dir="ltr">{household.invite_code}</strong><Button kind="soft" onClick={copy}>نسخ الرمز</Button></section><section className="card"><h3>أفراد المنزل</h3>{members.map((member) => <div className="member" key={member.user_id}><div className="member-avatar"><UserRound size={17}/></div><span>{member.profiles?.display_name || 'عضو في المنزل'}</span><small>{member.role === 'owner' ? 'المالك' : 'عضو'}</small></div>)}</section>{households.length > 1 && <section className="card"><h3>التبديل بين المنازل</h3>{households.map((item) => <button className="household-select" onClick={() => changeHousehold(item)} key={item.id}>{item.name}{item.id === household.id && <Check size={18}/>}</button>)}</section>}<Button kind="soft" onClick={onRefresh}><RotateCcw/>تحديث</Button></> }
function Profile({ user, onLogout, go, onError, deletionConfirmed }: { user: User; onLogout: () => Promise<void> | void; go: (view: View) => void; onError: (message: string) => void; deletionConfirmed: boolean }) { const [deletionRequested, setDeletionRequested] = useState(false); const [busy, setBusy] = useState(false); const sendDeletionEmail = async () => { if (!supabase || !user.email) return; setBusy(true); try { const { error } = await supabase.auth.signInWithOtp({ email: user.email, options: { shouldCreateUser: false, emailRedirectTo: `${window.location.origin}/?account_deletion=confirm` } }); if (error) throw error; setDeletionRequested(true) } catch (error) { onError(arabicError(error)) } finally { setBusy(false) } }; const deleteAccount = async () => { if (!window.confirm('سيُنقل ملكية العائلات إلى عضو آخر ثم يُحذف حسابك نهائياً. هل تريد المتابعة؟')) return; setBusy(true); try { await api.deleteAccount(); await onLogout() } catch (error) { onError(arabicError(error)) } finally { setBusy(false) } }; return <><section className="page-title"><UserRound/><div><h2>الملف والإعدادات</h2><p>{user.email}</p></div></section><button className="profile-household" onClick={() => go('household')}><span><UsersRound/><strong>العائلة</strong><small>عرض رمز الدعوة وإدارة الأعضاء</small></span><ArrowRight/></button><section className="card"><h3>حسابك</h3><p className="muted">تُحفظ الجلسة بأمان على هذا الجهاز، ويمكن تغيير كلمة المرور عبر رابط الاستعادة في شاشة الدخول.</p></section><section className="card danger-zone"><h3>حذف الحساب</h3>{deletionConfirmed ? <><p>تم تأكيد بريدك الإلكتروني. سيتم نقل ملكية كل عائلة إلى عضو آخر قبل حذف حسابك.</p><Button kind="danger" disabled={busy} onClick={deleteAccount}>حذف حسابي نهائياً</Button></> : <><p className="muted">سنرسل رابط تأكيد إلى بريدك. لا يمكن حذف الحساب قبل فتح الرابط.</p><Button kind="soft" disabled={busy} onClick={sendDeletionEmail}>إرسال رابط تأكيد الحذف</Button>{deletionRequested && <p className="notice">أرسلنا الرابط إلى بريدك الإلكتروني. افتحه لإتمام التأكيد.</p>}</>}</section><Button kind="danger" onClick={() => onLogout()}><LogOut/>تسجيل الخروج</Button></> }
function Loading() { return <div className="center-loading"><LoaderCircle className="spin"/> جارٍ التحميل…</div> }
